ANIMAL_DATA: dict[str, list[str]] = {
    "mammal": [
        "beaver",
        "panther",
        "lion",
        "llama",
        "colobus",
        "marmoset",
        "rabbit",
        "dingo",
        "pika",
        "okapi",
        "gazelle",
        "margay",
        "echidna",
        "vicuna",
        "grizzly",
        "aardvark",
        "anteater",
        "orangutan",
        "wallaby",
        "meerkat",
        "mongoose",
        "bongo",
        "hamster",
        "caracal",
        "whale",
        "addax",
        "boar",
        "puma",
        "peccary",
        "bonobo",
        "dolphin",
        "proboscis",
        "otter",
        "sheep",
        "capuchin",
        "howler",
        "guinea",
        "horse",
        "chinchilla",
        "donkey",
        "mandrill",
        "warthog",
        "galago",
        "takin",
        "impala",
        "eland",
        "springbok",
        "chimpanzee",
        "waterbuck",
        "moose",
        "nutria",
        "mink",
        "platypus",
        "mole",
        "ibex",
        "dormouse",
        "wolverine",
        "buffalo",
        "gorilla",
        "spermwhale",
        "fennec",
        "gerbil",
        "goat",
        "pangolin",
        "vole",
        "panda",
        "pronghorn",
        "polarbear",
        "gibbon",
        "jaguar",
        "fox",
        "agouti",
        "kudu",
        "snow-leopard",
        "finwhale",
        "gnu",
        "ape",
        "wombat",
        "tiger",
        "uakari",
        "dog",
        "saki",
        "hartebeest",
        "gemsbok",
        "pony",
        "redpanda",
        "jackal",
        "sloth",
        "alpaca",
        "muskox",
        "pig",
        "hedgehog",
        "coyote",
        "giraffe",
        "walrus",
        "narwhal",
        "rodent",
        "cougar",
        "serow",
        "cat",
        "yak",
        "kangaroo",
        "tarsier",
        "elk",
        "chimp",
        "bison",
        "capybara",
        "papio",
        "armadillo",
        "tamarin",
        "black-bear",
        "loris",
        "ermine",
        "weasel",
        "hare",
        "monkey",
        "oryx",
        "camel",
        "ocelot",
        "marten",
        "beluga",
        "antelope",
        "caribou",
        "macaque",
        "rhinoceros",
        "ferret",
        "muskrat",
        "cheetah",
        "raccoon",
        "opossum",
        "deer",
        "langur",
        "sable",
        "gaur",
        "dugong",
        "zebu",
        "mule",
        "hippopotamus",
        "badger",
        "wolf",
        "manatee",
        "wildebeest",
        "shrew",
        "elephant",
        "rat",
        "tapir",
        "stoat",
        "baboon",
        "reindeer",
        "sea-lion",
        "polar-bear",
        "guanaco",
        "orca",
        "zebra",
        "cow",
        "porcupine",
        "leopard",
        "mouse",
    ],
    "bird": [
        "wigeon",
        "parrot",
        "albatross",
        "cockatoo",
        "magpie",
        "cardinal",
        "honeyeater",
        "hummingbird",
        "sedge",
        "kinglet",
        "kingfisher",
        "rhea",
        "plover",
        "thrush",
        "raven",
        "pelican",
        "ibis",
        "redshank",
        "mockingbird",
        "goldfinch",
        "tinamou",
        "cassowary",
        "chaffinch",
        "woodpecker",
        "peafowl",
        "cuckoo",
        "loon",
        "sunbird",
        "emu",
        "roadrunner",
        "waxwing",
        "harrier",
        "curlew",
        "godwit",
        "goose",
        "vulture",
        "avocet",
        "wagtail",
        "manakin",
        "snipe",
        "vireo",
        "partridge",
        "jay",
        "sandpiper",
        "dipper",
        "gadwall",
        "woodcock",
        "cotinga",
        "antpitta",
        "lovebird",
        "ptarmigan",
        "grebe",
        "hawk",
        "teal",
        "gnateater",
        "budgerigar",
        "oystercatcher",
        "osprey",
        "owl",
        "finch",
        "kite",
        "lorikeet",
        "wren",
        "hornbill",
        "turkey",
        "buzzard",
        "nightingale",
        "treecreeper",
        "tanager",
        "shoveler",
        "greenfinch",
        "puffin",
        "tern",
        "jacamar",
        "egret",
        "antbird",
        "tapaculo",
        "thrasher",
        "eagle",
        "brambling",
        "smew",
        "moorhen",
        "blackbird",
        "phalarope",
        "oriole",
        "toucan",
        "junco",
        "goldeneye",
        "turaco",
        "bunting",
        "flamingo",
        "keel",
        "redpoll",
        "macaw",
        "parakeet",
        "heron",
        "hoopoe",
        "duck",
        "sparrow",
        "catbird",
        "mallard",
        "coot",
        "flycatcher",
        "quail",
        "nuthatch",
        "bee-eater",
        "lapwing",
        "chicken",
        "guineafowl",
        "grosbeak",
        "swallow",
        "phoebe",
        "linnet",
        "kakapo",
        "cisticola",
        "kestrel",
        "ostrich",
        "dunlin",
        "reedbunting",
        "lark",
        "dove",
        "pintail",
        "falcon",
        "bullfinch",
        "pipit",
        "swan",
        "starling",
        "pheasant",
        "kiwi",
        "eider",
        "grouse",
        "pigeon",
        "shrike",
        "stork",
        "warbler",
        "cormorant",
        "merganser",
        "crossbill",
        "seagull",
        "canary",
        "scoter",
        "siskin",
    ],
    "reptile": [
        "viper",
        "lizard",
        "terrapin",
        "cobra",
        "anaconda",
        "gila",
        "skink",
        "crocodile",
        "anole",
        "iguana",
        "chameleon",
        "mamba",
        "gecko",
        "komodo",
        "snake",
        "tortoise",
        "alligator",
        "turtle",
        "tuatara",
    ],
    "fish": [
        "snapper",
        "anchovy",
        "moonfish",
        "herring",
        "dolphinfish",
        "pomfret",
        "crab",
        "barracuda",
        "arowana",
        "ladyfish",
        "salmon",
        "dace",
        "scallop",
        "carp",
        "eel",
        "flounder",
        "spadefish",
        "tilapia",
        "boxfish",
        "croaker",
        "goosefish",
        "pollock",
        "trout",
        "seahorse",
        "shark",
        "jewfish",
        "grayling",
        "tench",
        "mahi-mahi",
        "halibut",
        "bonefish",
        "ide",
        "urchin",
        "piranha",
        "rockfish",
        "swordtail",
        "tuna",
        "surgeonfish",
        "smelt",
        "mackerel",
        "sockeye",
        "fluke",
        "chub",
        "starfish",
        "tarpon",
        "pompano",
        "monkfish",
        "moray",
        "cod",
        "catfish",
        "clam",
        "ribbonfish",
        "rudd",
        "sturgeon",
        "coho",
        "jellyfish",
        "bitterling",
        "grunt",
        "roach",
        "pipefish",
        "weakfish",
        "grouper",
        "snook",
        "swordfish",
        "lingcod",
        "clownfish",
        "oyster",
        "haddock",
        "angelfish",
        "mussel",
        "sardine",
        "platy",
        "scorpionfish",
        "chinook",
        "triggerfish",
        "amberjack",
        "sablefish",
        "guppy",
        "mahi",
        "discus",
        "puffer",
        "mullet",
        "lobster",
        "kingfish",
        "pleco",
        "whitefish",
        "perch",
        "gar",
        "barbel",
        "shrimp",
        "bream",
        "wrass",
        "pike",
        "damselfish",
        "lionfish",
        "goldfish",
        "cichlid",
        "bleak",
        "scup",
        "bluefish",
    ],
    "amphibian": [
        "bullfrog",
        "siren",
        "toad",
        "treefrog",
        "frog",
        "olm",
        "axolotl",
        "surinam",
        "natterjack",
        "hellbender",
        "salamander",
        "tadpole",
        "glassfrog",
        "mudpuppy",
        "newt",
        "caecilian",
    ],
    "insect": [
        "mayfly",
        "grasshopper",
        "bedbug",
        "silverfish",
        "cicada",
        "dragonfly",
        "lacewing",
        "leech",
        "butterfly",
        "damselfly",
        "housefly",
        "termite",
        "earwig",
        "slug",
        "moth",
        "flea",
        "earthworm",
        "mosquito",
        "hornet",
        "snail",
        "ladybug",
        "cockroach",
        "gnat",
        "scarab",
        "scorpion",
        "caterpillar",
        "aphid",
        "thrips",
        "weevil",
        "beetle",
        "tarantula",
        "firefly",
        "millipede",
        "spider",
        "cricket",
        "wasp",
        "ant",
        "centipede",
        "mite",
        "bee",
    ],
}

ANIMAL_OVERALL_CATEGORY: str = "animals"

FLOWERS_DATA: dict[str, list[str]] = {
    "Rose Family (Rosaceae)": [
        "Red Rose",
        "White Rose",
        "Pink Rose",
        "Yellow Rose",
        "Orange Rose",
        "Purple Rose",
        "Garden Rose",
        "Wild Rose",
        "Climbing Rose",
        "Tea Rose",
        "Hybrid Tea Rose",
        "Floribunda Rose",
        "Grandiflora Rose",
        "Shrub Rose",
        "Miniature Rose",
        "Rambling Rose",
        "English Rose",
        "Cabbage Rose",
        "Moss Rose",
        "Damask Rose",
        "Gallica Rose",
        "Alba Rose",
        "Bourbon Rose",
        "Noisette Rose",
        "China Rose",
        "Rugosa Rose",
        "Multiflora Rose",
        "Banksia Rose",
        "Cherokee Rose",
        "Cherry Blossom",
        "Apple Blossom",
        "Pear Blossom",
        "Plum Blossom",
        "Peach Blossom",
        "Apricot Blossom",
        "Almond Blossom",
        "Hawthorn Blossom",
        "Strawberry Blossom",
        "Raspberry Blossom",
        "Blackberry Blossom",
        "Gooseberry Blossom",
        "Currant Blossom",
        "Elderberry Blossom",
        "Rowan Blossom",
        "Whitebeam Blossom",
        "Service Tree Blossom",
        "Loquat Blossom",
        "Medlar Blossom",
        "Quince Blossom",
        "Japanese Quince",
        "Flowering Quince",
        "Chaenomeles",
        "Cydonia",
        "Pyrus Blossom",
        "Malus Blossom",
        "Spirea",
        "Bridal Wreath Spirea",
        "Japanese Spirea",
        "Bumald Spirea",
        "Anthony Waterer Spirea",
        "Goldflame Spirea",
        "Little Princess Spirea",
        "Shirobana Spirea",
        "Neon Flash Spirea",
        "Potentilla",
        "Cinquefoil",
        "Shrubby Cinquefoil",
        "Spring Cinquefoil",
        "Creeping Cinquefoil",
        "Lady's Mantle",
        "Alpine Lady's Mantle",
        "Meadowsweet",
        "Queen of the Meadow",
        "Dropwort",
        "Filipendula",
        "Mountain Ash Blossom",
        "European Mountain Ash",
        "American Mountain Ash",
        "Serviceberry",
        "Juneberry",
        "Saskatoon Berry",
        "Shadbush",
        "Amelanchier",
        "Cotoneaster",
        "Rock Cotoneaster",
        "Creeping Cotoneaster",
        "Pyracantha",
        "Firethorn",
        "Scarlet Firethorn",
        "Orange Firethorn",
        "Red Firethorn",
        "Mock Orange",
        "Sweet Mock Orange",
        "Pearl Bush",
        "Exochorda",
        "Kerria",
        "Japanese Kerria",
        "Ninebark",
        "Common Ninebark",
        "Eastern Ninebark",
        "Pacific Ninebark",
        "Chokeberry",
        "Black Chokeberry",
        "Red Chokeberry",
        "Purple Chokeberry",
        "Aronia",
        "Photinia",
        "Red Tip Photinia",
        "Chinese Photinia",
        "Japanese Photinia",
        "Fraser Photinia",
        "Toyon",
        "Christmas Berry",
        "Heteromeles",
        "Ocean Spray",
        "Holodiscus",
        "Cream Bush",
    ],
    "Daisy Family (Asteraceae)": [
        "Sunflower",
        "Common Sunflower",
        "Dwarf Sunflower",
        "Giant Sunflower",
        "Red Sunflower",
        "Mexican Sunflower",
        "Jerusalem Artichoke",
        "Sunchoke",
        "Common Daisy",
        "English Daisy",
        "Gerbera Daisy",
        "Shasta Daisy",
        "African Daisy",
        "Blue Daisy",
        "Swan River Daisy",
        "Livingstone Daisy",
        "Painted Daisy",
        "Gloriosa Daisy",
        "Ox-Eye Daisy",
        "Michaelmas Daisy",
        "Chrysanthemum",
        "Garden Mum",
        "Football Mum",
        "Pompon Mum",
        "Decorative Mum",
        "Button Mum",
        "Spider Mum",
        "Spoon Mum",
        "Anemone Mum",
        "Single Mum",
        "Korean Mum",
        "Feverfew",
        "Costmary",
        "Tanacetum",
        "Pyrethrum",
        "Painted Pyrethrum",
        "Aster",
        "New England Aster",
        "Aromatic Aster",
        "White Oldfield Aster",
        "Smooth Aster",
        "Fall-Blooming Aster",
        "China Aster",
        "Callistephus",
        "Monte Casino Aster",
        "September Aster",
        "Marigold",
        "French Marigold",
        "African Marigold",
        "Signet Marigold",
        "Marsh Marigold",
        "Pot Marigold",
        "Calendula",
        "English Marigold",
        "Field Marigold",
        "Desert Marigold",
        "Zinnia",
        "Common Zinnia",
        "Narrow-Leaf Zinnia",
        "Mexican Zinnia",
        "Creeping Zinnia",
        "Prairie Zinnia",
        "Giant Zinnia",
        "Dwarf Zinnia",
        "Cactus Zinnia",
        "Dahlia Zinnia",
        "Cosmos",
        "Common Cosmos",
        "Yellow Cosmos",
        "Chocolate Cosmos",
        "Orange Cosmos",
        "Sensation Cosmos",
        "Bipinnatus Cosmos",
        "Sulphureus Cosmos",
        "Atrosanguineus Cosmos",
        "Black-Eyed Susan",
        "Rudbeckia",
        "Goldsturm Rudbeckia",
        "Prairie Sun Rudbeckia",
        "Cherokee Sunset",
        "Gloriosa Rudbeckia",
        "Irish Eyes Rudbeckia",
        "Toto Rudbeckia",
        "Brown-Eyed Susan",
        "Three-Lobed Coneflower",
        "Purple Coneflower",
        "Echinacea",
        "White Swan Echinacea",
        "Magnus Echinacea",
        "Kim's Knee High",
        "Green Twister Echinacea",
        "Cheyenne Spirit",
        "Prairie Splendor",
        "Pink Double Delight",
        "Orange Meadowbrite",
        "Dahlia",
        "Dinner Plate Dahlia",
        "Cactus Dahlia",
        "Pompon Dahlia",
        "Decorative Dahlia",
        "Ball Dahlia",
        "Waterlily Dahlia",
        "Collarette Dahlia",
        "Anemone Dahlia",
        "Single Dahlia",
        "Peony Dahlia",
        "Semi-Cactus Dahlia",
        "Formal Decorative",
        "Informal Decorative",
        "Miniature Dahlia",
        "Chamomile",
        "German Chamomile",
        "Roman Chamomile",
        "Pineapple Weed",
        "False Chamomile",
        "Corn Chamomile",
        "Stinking Chamomile",
        "Wild Chamomile",
        "Dyer's Chamomile",
        "Sweet False Chamomile",
    ],
    "Lily Family (Liliaceae)": [
        "Easter Lily",
        "Madonna Lily",
        "Tiger Lily",
        "Turk's Cap Lily",
        "Wood Lily",
        "Canada Lily",
        "Martagon Lily",
        "Leopard Lily",
        "Regal Lily",
        "Trumpet Lily",
        "Orienpet Lily",
        "Longiflorum Lily",
        "Speciosum Lily",
        "Henryi Lily",
        "Regale Lily",
        "Candidum Lily",
        "Pardalinum Lily",
        "Superbum Lily",
        "Philadelphicum Lily",
        "Lancifolium Lily",
        "Asiatic Lily",
        "Oriental Lily",
        "LA Hybrid Lily",
        "LO Hybrid Lily",
        "OT Hybrid Lily",
        "Daylily",
        "Hemerocallis",
        "Stella de Oro Daylily",
        "Happy Returns Daylily",
        "Purple de Oro",
        "Pardon Me Daylily",
        "Chicago Apache",
        "Rosy Returns",
        "Joan Senior",
        "Ice Carnival",
        "Tulip",
        "Darwin Tulip",
        "Triumph Tulip",
        "Single Early Tulip",
        "Double Early Tulip",
        "Single Late Tulip",
        "Double Late Tulip",
        "Lily-Flowered Tulip",
        "Fringed Tulip",
        "Viridiflora Tulip",
        "Parrot Tulip",
        "Rembrandt Tulip",
        "Kaufmanniana Tulip",
        "Fosteriana Tulip",
        "Greigii Tulip",
        "Species Tulip",
        "Darwin Hybrid Tulip",
        "Multi-Flowering Tulip",
        "Botanical Tulip",
        "Wild Tulip",
        "Daffodil",
        "Narcissus",
        "Trumpet Daffodil",
        "Large-Cupped Daffodil",
        "Small-Cupped Daffodil",
        "Double Daffodil",
        "Triandrus Daffodil",
        "Cyclamineus Daffodil",
        "Jonquilla Daffodil",
        "Tazetta Daffodil",
        "Poeticus Daffodil",
        "Split-Corona Daffodil",
        "Miniature Daffodil",
        "Paper White",
        "King Alfred",
        "Ice Follies",
        "Carlton",
        "Mount Hood",
        "Dutch Master",
        "Golden Harvest",
        "Tete-a-Tete",
        "Hyacinth",
        "Dutch Hyacinth",
        "Grape Hyacinth",
        "Muscari",
        "Roman Hyacinth",
        "Feather Hyacinth",
        "Tassel Hyacinth",
        "Armenian Grape Hyacinth",
        "Common Grape Hyacinth",
        "Azure Grape Hyacinth",
        "Crocus",
        "Dutch Crocus",
        "Snow Crocus",
        "Giant Crocus",
        "Autumn Crocus",
        "Saffron Crocus",
        "Spring Crocus",
        "Cloth of Gold Crocus",
        "Species Crocus",
        "Tommasinianus Crocus",
        "Iris",
        "Bearded Iris",
        "Siberian Iris",
        "Japanese Iris",
        "Louisiana Iris",
        "Dutch Iris",
        "English Iris",
        "Spanish Iris",
        "Dwarf Iris",
        "Intermediate Iris",
        "Tall Bearded Iris",
        "Border Bearded Iris",
        "Miniature Dwarf Bearded Iris",
        "Standard Dwarf Bearded Iris",
        "Aril Iris",
        "Gladiolus",
        "Large-Flowered Gladiolus",
        "Miniature Gladiolus",
        "Primulinus Gladiolus",
        "Butterfly Gladiolus",
        "Freesia",
        "Amaryllis",
        "Hippeastrum",
        "Belladonna Lily",
        "Naked Lady",
    ],
    "Orchid Family (Orchidaceae)": [
        "Phalaenopsis",
        "Moth Orchid",
        "White Phalaenopsis",
        "Pink Phalaenopsis",
        "Purple Phalaenopsis",
        "Yellow Phalaenopsis",
        "Spotted Phalaenopsis",
        "Mini Phalaenopsis",
        "Multiflora Phalaenopsis",
        "Novelty Phalaenopsis",
        "Cattleya",
        "Queen of Orchids",
        "Corsage Orchid",
        "Labiata Cattleya",
        "Trianae Cattleya",
        "Mossiae Cattleya",
        "Warscewiczii Cattleya",
        "Dowiana Cattleya",
        "Aurea Cattleya",
        "Percivaliana Cattleya",
        "Dendrobium",
        "Noble Dendrobium",
        "Nobile Dendrobium",
        "Phalaenopsis Dendrobium",
        "Kingianum Dendrobium",
        "Speciosum Dendrobium",
        "Aggregatum Dendrobium",
        "Chrysotoxum Dendrobium",
        "Fimbriatum Dendrobium",
        "Pierardii Dendrobium",
        "Oncidium",
        "Dancing Lady Orchid",
        "Golden Shower Orchid",
        "Tiger Orchid",
        "Chocolate Orchid",
        "Sharry Baby",
        "Sweet Fragrance",
        "Sphacelatum Oncidium",
        "Flexuosum Oncidium",
        "Ornithorhynchum Oncidium",
        "Cymbidium",
        "Boat Orchid",
        "Standard Cymbidium",
        "Miniature Cymbidium",
        "Pendulous Cymbidium",
        "Green Cymbidium",
        "White Cymbidium",
        "Pink Cymbidium",
        "Yellow Cymbidium",
        "Brown Cymbidium",
        "Paphiopedilum",
        "Lady Slipper Orchid",
        "Venus Slipper",
        "Maudiae Paphiopedilum",
        "Barbatum Paphiopedilum",
        "Insigne Paphiopedilum",
        "Spicerianum Paphiopedilum",
        "Fairrieanum Paphiopedilum",
        "Villosum Paphiopedilum",
        "Callosum Paphiopedilum",
        "Vanda",
        "Blue Vanda",
        "Coerulea Vanda",
        "Sanderiana Vanda",
        "Tessellata Vanda",
        "Tricolor Vanda",
        "Dearei Vanda",
        "Lamellata Vanda",
        "Limbata Vanda",
        "Luzonica Vanda",
        "Miltonia",
        "Pansy Orchid",
        "Spectabilis Miltonia",
        "Candida Miltonia",
        "Clowesii Miltonia",
        "Flavescens Miltonia",
        "Regnellii Miltonia",
        "Warscewiczii Miltonia",
        "Vexillaria Miltonia",
        "Roezlii Miltonia",
        "Odontoglossum",
        "Tiger Orchid",
        "Grande Odontoglossum",
        "Crispum Odontoglossum",
        "Luteopurpureum Odontoglossum",
        "Rossii Odontoglossum",
        "Triumphans Odontoglossum",
        "Bictonense Odontoglossum",
        "Cordatum Odontoglossum",
        "Nebulosum Odontoglossum",
        "Brassia",
        "Spider Orchid",
        "Rex Brassia",
        "Verrucosa Brassia",
        "Caudata Brassia",
        "Longissima Brassia",
        "Maculata Brassia",
        "Gireoudiana Brassia",
        "Arcuigera Brassia",
        "Lawrenceana Brassia",
        "Zygopetalum",
        "Crinitum Zygopetalum",
        "Intermedium Zygopetalum",
        "Mackayii Zygopetalum",
        "Maxillare Zygopetalum",
        "Masdevallia",
        "Kite Orchid",
        "Veitchiana Masdevallia",
        "Coccinea Masdevallia",
        "Tovarensis Masdevallia",
        "Bulbophyllum",
        "Medusae Bulbophyllum",
        "Rothschildianum Bulbophyllum",
        "Lobbii Bulbophyllum",
        "Elizabeth Ann Bulbophyllum",
    ],
}

FLOWERS_OVERALL_CATEGORY: str = "flowers"

def shorten_dict(
    input_dict: dict[str, list[str]], max_length: int = 5
) -> dict[str, list[str]]:
    return {k: v[:max_length] for k, v in input_dict.items()}
